"""Add updated models

Revision ID: 686599b03eb6
Revises: 3af3376fb9d9
Create Date: 2023-06-07 22:07:35.172567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686599b03eb6'
down_revision = '3af3376fb9d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
